name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: '**/*.csproj'

      - name: Build
        run: ./build --configuration Release --version-suffix ci --build-number "${GITHUB_RUN_NUMBER}"

      - name: Test
        run: ./test --configuration Release --no-restore --no-build
